/* DON'T EDIT THIS FILE. This is generated by 'scripts/lib/update-lib-index.js' */
"use strict";

module.exports = {
    configs: {
        recommended: require("./configs/recommended")
    },
    rules: {
        "curly-brace-newline": require("./rules/curly-brace-newline"),
        "export-alias": require("./rules/export-alias"),
        "no-undefined-return": require("./rules/no-undefined-return"),
        "simple-null-check": require("./rules/simple-null-check")
    }
};
