/* DON'T EDIT THIS FILE. This is generated by 'scripts/lib/update-lib-configs-recommended.js' */
"use strict";

module.exports = {
    plugins: ["brd"],
    rules: {
        "brd/curly-brace-newline": "error",
        "brd/export-alias": "error",
        "brd/no-undefined-return": "error",
        "brd/operator-space": "error"
    }
};
